
# Loads default set of integrations. Do not remove.
default_config:

logger:
  default: warn
  logs:
    custom_components.enslaved_thermostat: debug

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

input_boolean:
  virtual_heater:
    name: Virtual Heater
    icon: mdi:radiator

input_number:
  virtual_temp_sensor:
    name: Virtual temperature sensor
    icon: mdi:thermometer
    min: -20
    max: 40
    step: 0.1
    mode: box
    unit_of_measurement: °C

climate:
  - platform: enslaved_thermostat
    name: Virtual thermostat
    heater: input_boolean.virtual_heater
    target_sensor: input_number.virtual_temp_sensor
